# Generated by Django 3.1.1 on 2020-09-11 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(db_index=True, help_text='EAN13', max_length=13)),
                ('expiry_date', models.DateField(db_index=True, help_text='Expiry date')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Created on')),
            ],
            options={
                'unique_together': {('reference_id', 'expiry_date')},
            },
        ),
    ]
